Repository Spark-Project-Pulse/codehive-frontend, pull requests merged in 2024-11, with the labels that each got.

#49 Refactor: merge question card into component
  package-lock.json
  package.json
  src/app/questions/browse/page.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/universal/sidebar/app-sidebar.tsx
Labels: enhancement

#50 Refactor `browse` questions page
  src/app/communities/browse/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/app/questions/browse/page.tsx
  src/components/pages/communities/browse/SkeletonCommunityCard.tsx
  src/components/pages/questions/[question_id]/AnswerCard.tsx
  src/components/pages/questions/[question_id]/AnswerForm.tsx
  src/components/pages/questions/[question_id]/CommentCard.tsx
  src/components/pages/questions/[question_id]/CommentForm.tsx
  src/components/pages/questions/[question_id]/SkeletonAnswerCard.tsx
  src/components/pages/questions/[question_id]/SkeletonCommentCard.tsx
  src/components/pages/questions/[question_id]/SkeletonQuestionCard.tsx
Labels: enhancement, fix

#55 General refactors and fixes
  src/components/pages/communities/[community_title]/ContributorCard.tsx
  src/components/pages/questions/[question_id]/AnswerCard.tsx
  src/components/pages/questions/[question_id]/CommentCard.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/universal/SignOutButton.tsx
  src/components/universal/sidebar/nav-user.tsx
  src/types/Comments.ts
  src/types/Questions.ts
Labels: fix

#57 Feat/will/notifications frontend
  package-lock.json
  package.json
  src/api/notifications.ts
  src/app/notifications/page.tsx
  src/components/pages/notifications/columns.tsx
  src/components/ui/data-table.tsx
  src/components/ui/table.tsx
  src/components/universal/sidebar/nav-user.tsx
  src/types/Notifications.ts
  src/utils/notifications.tsx
Labels: feature

#63 Show/hide comments + theme styling
  src/app/globals.css
  src/app/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/components/pages/questions/[question_id]/AnswerCard.tsx
  src/components/pages/questions/[question_id]/CollapsibleComments.tsx
  src/components/ui/button.tsx
  src/components/universal/sidebar/ThemeToggle.tsx
Labels: enhancement

#59 initial version of file browser, context view within the question,fixed browser error with dark mode styles, and modified github api fetch
  public/github-logo-black.svg
  src/app/layout.tsx
  src/app/projects/[project_id]/browse-files/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/universal/code/CodeViewer.tsx
  src/components/universal/code/FileBrowser.tsx
  src/lib/github.ts
  src/types/Api.ts
  src/types/FileSystem.ts
  src/types/Projects.ts
  src/types/Questions.ts
Labels: feature, fix

#65 Feat/will/notifications continued
  src/api/auth.ts
  src/api/notifications.ts
  src/api/users.ts
  src/app/notifications/page.tsx
  src/components/pages/notifications/columns.tsx
  src/components/universal/sidebar/app-sidebar.tsx
  src/components/universal/sidebar/nav-user.tsx
  src/lib/constants/time.ts
  src/lib/cookies.ts
  src/types/Api.ts
  src/types/Notifications.ts
  src/utils/notifications.tsx
Labels: enhancement, feature

#66 Created AI code review feature
  package-lock.json
  package.json
  src/api/projects.ts
  src/app/admin/dashboard/page.tsx
  src/app/projects/[project_id]/browse-files/page.tsx
  src/app/projects/[project_id]/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/components/pages/admin/dashboard/CommunityRequestsTab.tsx
  src/components/ui/scroll-area.tsx
  src/components/universal/code/CodeViewer.tsx
  src/components/universal/code/FileBrowser.tsx
  src/types/Projects.ts
Labels: feature

#67 Fixed cookies `maxAge` and abstracted `Time` lib function
  src/lib/constants/time.ts
  src/lib/cookies.ts
Labels: enhancement, fix

#68 Feature/added skeletons
  public/github-logo-dark.svg
  public/github-logo-light.svg
  public/github-logo.png
  src/app/admin/dashboard/page.tsx
  src/app/communities/[community_title]/page.tsx
  src/app/profiles/[username]/page.tsx
  src/app/projects/[project_id]/browse-files/page.tsx
  src/app/projects/[project_id]/page.tsx
  src/app/projects/add-project/page.tsx
  src/components/pages/admin/dashboard/AdminDashboardSkeleton.tsx
  src/components/pages/communities/[community_title]/CommunityHeader.tsx
  src/components/pages/communities/[community_title]/CommunityQuestionsTab.tsx
  src/components/pages/communities/[community_title]/CommunitySkeleton.tsx
  src/components/pages/profiles/ProfileSkeleton.tsx
  src/components/pages/profiles/ProjectsSkeleton.tsx
  src/components/pages/profiles/QuestionsSkeleton.tsx
  src/components/pages/projects/[project_id]/ProjectSkeleton.tsx
  src/components/pages/projects/[project_id]/browse-files/BrowseFilesSkeleton.tsx
  src/components/pages/projects/add-project/ProjectForm.tsx
  src/components/pages/questions/ask-question/QuestionForm.tsx
  src/components/skeletons/AdminDashboardSkeleton.tsx
  src/components/universal/sidebar/app-sidebar.tsx
  src/components/universal/sidebar/nav-admin.tsx
  src/components/universal/sidebar/nav-communities.tsx
  src/components/universal/sidebar/nav-projects.tsx
  src/lib/github.ts
  src/types/Projects.ts
Labels: feature

#70 Hotfix/will/debug create user
  .env.production
  src/components/pages/questions/[question_id]/AnswerCard.tsx
Labels: fix

#73 Added auth redirect popup for auth required actions
  public/anon-user-pfp.jpg
  src/api/answers.ts
  src/api/comments.ts
  src/api/communities.ts
  src/api/users.ts
  src/app/communities/[community_title]/page.tsx
  src/app/communities/create/page.tsx
  src/app/profiles/[username]/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/app/questions/answer-question/page.tsx
  src/components/pages/admin/dashboard/CommunityRequestsTab.tsx
  src/components/pages/communities/[community_title]/CommunityHeader.tsx
  src/components/pages/communities/create/CommunityForm.tsx
  src/components/pages/questions/[question_id]/AnswerCard.tsx
  src/components/universal/ButtonWithLoading.tsx
  src/components/universal/NotAuthenticatedPopup.tsx
  src/components/universal/sidebar/app-sidebar.tsx
  src/components/universal/sidebar/nav-user.tsx
  src/types/Answers.ts
Labels: feature
