Repository Spark-Project-Pulse/codehive-frontend, pull requests merged in 2024-10, with the labels that each got.

#3 Refactored eslint
  .eslintrc.json
  .prettierignore
  package-lock.json
  package.json
  src/app/ask-question/page.tsx
  src/app/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/components/ui/form.tsx
  src/components/ui/use-toast.tsx
  src/types/Question.ts
  tailwind.config.ts
Labels: enhancement

#4 Completed navbar. Added dummy login, signup, answer question pages. Added placeholder for logo. Created custom 404 page.
  src/app/answer-question/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/sign-up/page.tsx
  src/components/Navbar.tsx
Labels: feature

#6 Feature/respond question mensun
  src/app/questions/[question_id]/page.tsx
  src/components/answer-question/AnswerForm.tsx
  src/types/Answer.ts
Labels: feature

#8 Feat/will/create project frontend
  package-lock.json
  package.json
  src/app/projects/[project_id]/page.tsx
  src/app/projects/add-project/page.tsx
  src/components/Navbar.tsx
  src/components/projects/add-project/ProjectForm.tsx
  src/components/ui/badge.tsx
  src/components/ui/select.tsx
  src/types/Projects.ts
Labels: feature

#14 added artifact registry policy & workflow, and added pr-dependency policy and workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/artifact-policy-deploy.yml
  .github/workflows/pr-dependencies.yml
  artifact-registry-policy.json
Labels: feature

#21 Hotfix/adjust minimum docker instances
  .github/workflows/artifact-policy-deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#23 Feature/comments4answers mensun
  src/api/comments.ts
  src/app/globals.css
  src/app/questions/[question_id]/page.tsx
  src/components/pages/questions/[question_id]/CommentForm.tsx
  src/types/Comments.ts
  tailwind.config.ts
Labels: feature

#24 Linked github repo to project (frontend)
  src/app/projects/add-project/[user_id]/page.tsx
  src/app/projects/add-project/page.tsx
  src/components/pages/projects/add-project/ProjectForm.tsx
  src/components/universal/Navbar.tsx
  src/types/Projects.ts
Labels: feature

#25 Initial attempt at rendering files from GitHub
  src/app/projects/[project_id]/browse-files/page.tsx
  src/app/projects/[project_id]/page.tsx
  src/types/Projects.ts
Labels: feature

#22 Feature/google secrets manager
  .env.development
  .env.production
  .github/workflows/deploy.yml
  .gitignore
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/api/auth.ts
  src/app/auth/callback/route.ts
  src/lib/getSecret.ts
  src/utils/supabase/server.ts
Labels: feature

#38 Removed redundant user fetch
  src/app/projects/add-project/page.tsx
Labels: fix

#43 Replaced navbar with shadcn `Sidebar`
  package-lock.json
  package.json
  public/logo.svg
  src/app/dashboard/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/questions/view-all-questions/page.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/collapsible.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/tooltip.tsx
  src/components/universal/Navbar.tsx
  src/components/universal/sidebar/app-sidebar.tsx
  src/components/universal/sidebar/nav-main.tsx
  src/components/universal/sidebar/nav-projects.tsx
  src/components/universal/sidebar/nav-user.tsx
  src/hooks/use-mobile.tsx
  src/hooks/useKeyboardShortcut.ts
  src/styles/readme.md
  tailwind.config.ts
Labels: enhancement, feature

#44 Reputation and upvote/downvote system created
  src/api/answers.ts
  src/api/users.ts
  src/app/projects/add-project/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/components/pages/questions/[question_id]/AnswerCard.tsx
  src/components/pages/questions/[question_id]/CommentCard.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/ui/MultiSelector.tsx
  src/types/Answers.ts
  src/types/Api.ts
Labels: enhancement, feature

#45 Connect question to project (`context`)
  package-lock.json
  package.json
  src/app/projects/[project_id]/browse-files/page.tsx
  src/app/questions/ask-question/page.tsx
  src/components/pages/questions/ask-question/QuestionForm.tsx
  src/components/universal/code/CodeViewer.tsx
  src/lib/github.ts
  src/types/Projects.ts
  src/types/Questions.ts
Labels: feature

#48 Initial community implementation
  public/default-community-avatar.png
  src/api/communities.ts
  src/app/communities/[community_title]/page.tsx
  src/app/communities/browse/page.tsx
  src/app/questions/view-all-questions/page.tsx
  src/components/pages/communities/[community_title]/CommunityHeader.tsx
  src/components/pages/communities/browse/CommunityCard.tsx
  src/components/pages/communities/browse/CommunityCardSkeleton.tsx
  src/components/ui/pagination.tsx
  src/components/universal/search/ActiveFilters.tsx
  src/components/universal/search/PaginationComponent.tsx
  src/components/universal/search/SearchAndTagComponent.tsx
  src/components/universal/sidebar/app-sidebar.tsx
  src/components/universal/sidebar/nav-communities.tsx
  src/types/Api.ts
  src/types/Communities.ts
Labels: feature
