Repository Spark-Project-Pulse/codehive-frontend, pull requests merged in 2024-12, with the labels that each got.

#76 Refactored the project page
  package-lock.json
  package.json
  src/app/communities/browse/page.tsx
  src/app/projects/[project_id]/browse-files/page.tsx
  src/app/projects/[project_id]/page.tsx
  src/app/questions/browse/page.tsx
  src/components/pages/communities/[community_title]/CommunityQuestionsTab.tsx
  src/components/pages/projects/[project_id]/BrowseFilesSkeleton.tsx
  src/components/pages/projects/[project_id]/ProjectHeader.tsx
  src/components/pages/projects/[project_id]/ProjectHeaderSkeleton.tsx
  src/components/pages/projects/[project_id]/ProjectSkeleton.tsx
  src/components/pages/projects/[project_id]/SuggestionsPanel.tsx
  src/components/ui/bento-grid.tsx
  src/components/ui/resizable.tsx
  src/components/universal/code/FileBrowser.tsx
  src/components/universal/sidebar/app-sidebar.tsx
Labels: enhancement

#77 Added update/delete for question
  src/api/questions.ts
  src/app/profiles/[username]/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/pages/questions/[question_id]/UpdateDeleteQuestionDialog.tsx
  src/components/pages/questions/[question_id]/UpdateQuestionForm.tsx
Labels: feature

#84 Feat/will/markdown editor
  package-lock.json
  package.json
  src/app/communities/create/page.tsx
  src/app/globals.css
  src/app/projects/add-project/page.tsx
  src/app/questions/ask-question/page.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/pages/questions/[question_id]/UpdateDeleteQuestionDialog.tsx
  src/components/pages/questions/[question_id]/UpdateQuestionForm.tsx
  src/components/pages/questions/ask-question/QuestionForm.tsx
  src/components/universal/code/DynamicMarkdownPreview.tsx
  src/components/universal/code/MarkdownEditor.tsx
  src/global.d.ts
Labels: enhancement, feature

#88 Addressed several UI bugs
  public/hive-bg-dark.svg
  public/hive-bg-light.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/questions/[question_id]/page.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/ui/button.tsx
  src/components/universal/footer/footer.tsx
Labels: fix

#87 General hotfixes
  src/app/hives/create/page.tsx
  src/app/profiles/[username]/page.tsx
  src/app/projects/add-project/page.tsx
  src/app/questions/ask-question/page.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/pages/questions/[question_id]/UpdateDeleteQuestionDialog.tsx
  src/components/pages/questions/[question_id]/UpdateQuestionForm.tsx
  src/components/universal/code/CodeViewer.tsx
  src/components/universal/code/FileBrowser.tsx
  src/components/universal/code/MarkdownEditor.tsx
  src/utils/codeEditorHelpers.tsx
Labels: enhancement

#90 Hive hotfix
  src/api/hives.ts
  src/app/globals.css
  src/app/hives/browse/page.tsx
  src/app/page.tsx
  src/app/questions/browse/page.tsx
  src/components/pages/hives/browse/HiveCard.tsx
Labels: fix

#94 Refactor/will/multiple lines code
  src/api/questions.ts
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  src/components/pages/questions/ask-question/QuestionForm.tsx
  src/components/universal/code/CodeViewer.tsx
  src/components/universal/code/ReadOnlyEditor.tsx
  src/types/Questions.ts
Labels: enhancement

#95 Random fixes
  src/components/pages/hives/[hive_title]/HiveHeader.tsx
  src/components/pages/home/Hero.tsx
Labels: fix

#96 Fix/will/design implementation
  src/app/fonts/Sigmar-Regular.ttf
  src/app/globals.css
  src/app/hives/create/page.tsx
  src/app/login/page.tsx
  src/app/profiles/[username]/page.tsx
  src/app/projects/add-project/page.tsx
  src/app/questions/ask-question/page.tsx
  src/components/pages/hives/[hive_title]/ContributorCard.tsx
  src/components/pages/hives/browse/HiveCard.tsx
  src/components/pages/hives/browse/SkeletonHiveCard.tsx
  src/components/pages/home/Hero.tsx
  src/components/pages/login/FeatureCard.tsx
  src/components/pages/questions/[question_id]/QuestionCard.tsx
  tailwind.config.ts
Labels: enhancement
